/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JFrame;

/**
 *
 * @author agust
 */
public class Probabilidades extends javax.swing.JFrame {
    
    public static Probabilidades instanciaProbabilidades;
    /**
     * Creates new form Probabilidades
     */
    public Probabilidades() {
        initComponents();
        this.setSize(1280, 760);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciarFrame = new javax.swing.JFrame();
        atrasBoton = new javax.swing.JButton();
        historiaBoton = new javax.swing.JButton();
        teoriaBoton = new javax.swing.JButton();
        ejerciciosBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        creditosFrame = new javax.swing.JFrame();
        atrasBoton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        historiaFrame = new javax.swing.JFrame();
        pag2Boton = new javax.swing.JButton();
        atrasBoton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        historiaFrame1 = new javax.swing.JFrame();
        pag3Boton = new javax.swing.JButton();
        pag1Boton = new javax.swing.JButton();
        atrasBoton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        historiaFrame2 = new javax.swing.JFrame();
        atrasBoton4 = new javax.swing.JButton();
        pag4Boton = new javax.swing.JButton();
        pag2Boton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        historiaFrame3 = new javax.swing.JFrame();
        atrasBoton5 = new javax.swing.JButton();
        pag3Boton1 = new javax.swing.JButton();
        pag5Boton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        historiaFrame4 = new javax.swing.JFrame();
        atrasBoton6 = new javax.swing.JButton();
        pag4Boton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        teoriaFrame = new javax.swing.JFrame();
        reglasBoton = new javax.swing.JButton();
        conceptosBoton = new javax.swing.JButton();
        distribucionBoton = new javax.swing.JButton();
        atrasBoton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        reglasFrame = new javax.swing.JFrame();
        atrasBoton8 = new javax.swing.JButton();
        sumaBoton = new javax.swing.JButton();
        multiplicacionBoton = new javax.swing.JButton();
        laplaceBoton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        sumaFrame = new javax.swing.JFrame();
        atrasBoton9 = new javax.swing.JButton();
        ejemploBoton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ejemplosumaFrame = new javax.swing.JFrame();
        atrasBoton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        multiplicacionFrame = new javax.swing.JFrame();
        atrasBoton11 = new javax.swing.JButton();
        ejemploBoton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ejemplomultiplicacionFrame = new javax.swing.JFrame();
        atrasBoton12 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        laplaceFrame = new javax.swing.JFrame();
        atrasBoton13 = new javax.swing.JButton();
        ejemploBoton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        ejemplolaplaceFrame = new javax.swing.JFrame();
        atrasBoton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        conceptosFrame = new javax.swing.JFrame();
        atrasBoton15 = new javax.swing.JButton();
        siguienteBoton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        conceptosFrame1 = new javax.swing.JFrame();
        atrasBoton16 = new javax.swing.JButton();
        anteriorBoton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        distribucionFrame = new javax.swing.JFrame();
        atrasBoton17 = new javax.swing.JButton();
        ejemploBoton3 = new javax.swing.JButton();
        ejemploBoton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        ejemplocontinuaFrame = new javax.swing.JFrame();
        atrasBoton18 = new javax.swing.JButton();
        ejemplodiscretaFrame = new javax.swing.JFrame();
        atrasBoton19 = new javax.swing.JButton();
        ejerciciosFrame = new javax.swing.JFrame();
        atrasBoton20 = new javax.swing.JButton();
        iniciarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        creditosBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        iniciarFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });
        iniciarFrame.getContentPane().add(atrasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        historiaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/HISTORIA.png"))); // NOI18N
        historiaBoton.setMaximumSize(new java.awt.Dimension(340, 120));
        historiaBoton.setMinimumSize(new java.awt.Dimension(340, 120));
        historiaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaBotonActionPerformed(evt);
            }
        });
        iniciarFrame.getContentPane().add(historiaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 340, 120));

        teoriaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/TEORIA.png"))); // NOI18N
        teoriaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teoriaBotonActionPerformed(evt);
            }
        });
        iniciarFrame.getContentPane().add(teoriaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 340, 120));

        ejerciciosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJERCICIOS.png"))); // NOI18N
        ejerciciosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejerciciosBotonActionPerformed(evt);
            }
        });
        iniciarFrame.getContentPane().add(ejerciciosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 340, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PROBABILIDADES background.png"))); // NOI18N
        iniciarFrame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        creditosFrame.setMinimumSize(new java.awt.Dimension(1280, 720));
        creditosFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton1.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton1.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton1ActionPerformed(evt);
            }
        });
        creditosFrame.getContentPane().add(atrasBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/CREDITOS into.png"))); // NOI18N
        creditosFrame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        historiaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pag2Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 2.png"))); // NOI18N
        pag2Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag2BotonActionPerformed(evt);
            }
        });
        historiaFrame.getContentPane().add(pag2Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 120, 60));

        atrasBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS w.png"))); // NOI18N
        atrasBoton2.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton2.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton2ActionPerformed(evt);
            }
        });
        historiaFrame.getContentPane().add(atrasBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("1");
        historiaFrame.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 20, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/Historia 1.jpg"))); // NOI18N
        historiaFrame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        historiaFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pag3Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 3.png"))); // NOI18N
        pag3Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag3BotonActionPerformed(evt);
            }
        });
        historiaFrame1.getContentPane().add(pag3Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 120, 60));

        pag1Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 1.png"))); // NOI18N
        pag1Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag1BotonActionPerformed(evt);
            }
        });
        historiaFrame1.getContentPane().add(pag1Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 120, 60));

        atrasBoton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton3.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton3.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton3ActionPerformed(evt);
            }
        });
        historiaFrame1.getContentPane().add(atrasBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("2");
        historiaFrame1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 20, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/HISTORIA 2.jpg"))); // NOI18N
        historiaFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        historiaFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS w.png"))); // NOI18N
        atrasBoton4.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton4.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton4ActionPerformed(evt);
            }
        });
        historiaFrame2.getContentPane().add(atrasBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        pag4Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 4.png"))); // NOI18N
        pag4Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag4BotonActionPerformed(evt);
            }
        });
        historiaFrame2.getContentPane().add(pag4Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 120, 60));

        pag2Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 2.png"))); // NOI18N
        pag2Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag2Boton1ActionPerformed(evt);
            }
        });
        historiaFrame2.getContentPane().add(pag2Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 120, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("3");
        historiaFrame2.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 20, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/HISTORIA 3.jpg"))); // NOI18N
        historiaFrame2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        historiaFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton5.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton5.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton5ActionPerformed(evt);
            }
        });
        historiaFrame3.getContentPane().add(atrasBoton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        pag3Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 3.png"))); // NOI18N
        pag3Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag3Boton1ActionPerformed(evt);
            }
        });
        historiaFrame3.getContentPane().add(pag3Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 120, 60));

        pag5Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 5.png"))); // NOI18N
        pag5Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag5BotonActionPerformed(evt);
            }
        });
        historiaFrame3.getContentPane().add(pag5Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 120, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("4");
        historiaFrame3.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 20, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/HISTORIA 4.jpg"))); // NOI18N
        historiaFrame3.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        historiaFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS w.png"))); // NOI18N
        atrasBoton6.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton6.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton6ActionPerformed(evt);
            }
        });
        historiaFrame4.getContentPane().add(atrasBoton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        pag4Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PAG 4.png"))); // NOI18N
        pag4Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag4Boton1ActionPerformed(evt);
            }
        });
        historiaFrame4.getContentPane().add(pag4Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 120, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("5");
        historiaFrame4.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/HISTORIA 5.jpg"))); // NOI18N
        historiaFrame4.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        teoriaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reglasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/REGLAS boton.png"))); // NOI18N
        reglasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglasBotonActionPerformed(evt);
            }
        });
        teoriaFrame.getContentPane().add(reglasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 340, 120));

        conceptosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/CONCEPTOS boton.png"))); // NOI18N
        conceptosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptosBotonActionPerformed(evt);
            }
        });
        teoriaFrame.getContentPane().add(conceptosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 340, 120));

        distribucionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/DISTRIBUCION boton.png"))); // NOI18N
        distribucionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribucionBotonActionPerformed(evt);
            }
        });
        teoriaFrame.getContentPane().add(distribucionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 340, 120));

        atrasBoton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton7.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton7.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton7ActionPerformed(evt);
            }
        });
        teoriaFrame.getContentPane().add(atrasBoton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/TEORIA back.jpg"))); // NOI18N
        teoriaFrame.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        reglasFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton8.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton8.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton8ActionPerformed(evt);
            }
        });
        reglasFrame.getContentPane().add(atrasBoton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        sumaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/SUMA boton.png"))); // NOI18N
        sumaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBotonActionPerformed(evt);
            }
        });
        reglasFrame.getContentPane().add(sumaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 340, 120));

        multiplicacionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/MULTIPLICACION boton.png"))); // NOI18N
        multiplicacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionBotonActionPerformed(evt);
            }
        });
        reglasFrame.getContentPane().add(multiplicacionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 340, 120));

        laplaceBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/LAPLACE boton.png"))); // NOI18N
        laplaceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laplaceBotonActionPerformed(evt);
            }
        });
        reglasFrame.getContentPane().add(laplaceBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 340, 120));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/REGLAS.jpg"))); // NOI18N
        reglasFrame.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        sumaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton9.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton9.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton9ActionPerformed(evt);
            }
        });
        sumaFrame.getContentPane().add(atrasBoton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        ejemploBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJEMPLO.jpg"))); // NOI18N
        ejemploBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBotonActionPerformed(evt);
            }
        });
        sumaFrame.getContentPane().add(ejemploBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 120, 60));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/SUMA.jpg"))); // NOI18N
        sumaFrame.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ejemplosumaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton10.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton10.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton10ActionPerformed(evt);
            }
        });
        ejemplosumaFrame.getContentPane().add(atrasBoton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));
        ejemplosumaFrame.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        multiplicacionFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton11.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton11.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton11ActionPerformed(evt);
            }
        });
        multiplicacionFrame.getContentPane().add(atrasBoton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        ejemploBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJEMPLO.jpg"))); // NOI18N
        ejemploBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBoton1ActionPerformed(evt);
            }
        });
        multiplicacionFrame.getContentPane().add(ejemploBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 120, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/MULTIPLICACION.jpg"))); // NOI18N
        multiplicacionFrame.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ejemplomultiplicacionFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton12.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton12.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton12ActionPerformed(evt);
            }
        });
        ejemplomultiplicacionFrame.getContentPane().add(atrasBoton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));
        ejemplomultiplicacionFrame.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        laplaceFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton13.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton13.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton13ActionPerformed(evt);
            }
        });
        laplaceFrame.getContentPane().add(atrasBoton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        ejemploBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJEMPLO.jpg"))); // NOI18N
        ejemploBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBoton2ActionPerformed(evt);
            }
        });
        laplaceFrame.getContentPane().add(ejemploBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 120, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/LAPLACE.jpg"))); // NOI18N
        laplaceFrame.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ejemplolaplaceFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton14.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton14.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton14ActionPerformed(evt);
            }
        });
        ejemplolaplaceFrame.getContentPane().add(atrasBoton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));
        ejemplolaplaceFrame.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        conceptosFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton15.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton15.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton15ActionPerformed(evt);
            }
        });
        conceptosFrame.getContentPane().add(atrasBoton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        siguienteBoton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/SIGUIENTE.png"))); // NOI18N
        siguienteBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBoton3ActionPerformed(evt);
            }
        });
        conceptosFrame.getContentPane().add(siguienteBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 120, 60));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/CONCEPTOS 1.jpg"))); // NOI18N
        conceptosFrame.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        conceptosFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton16.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton16.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton16ActionPerformed(evt);
            }
        });
        conceptosFrame1.getContentPane().add(atrasBoton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        anteriorBoton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ANTERIOR.png"))); // NOI18N
        anteriorBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBoton4ActionPerformed(evt);
            }
        });
        conceptosFrame1.getContentPane().add(anteriorBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 120, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/CONCEPTOS 2.jpg"))); // NOI18N
        conceptosFrame1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        distribucionFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton17.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton17.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton17ActionPerformed(evt);
            }
        });
        distribucionFrame.getContentPane().add(atrasBoton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        ejemploBoton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJEMPLO.jpg"))); // NOI18N
        ejemploBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBoton3ActionPerformed(evt);
            }
        });
        distribucionFrame.getContentPane().add(ejemploBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 120, 60));

        ejemploBoton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/EJEMPLO.jpg"))); // NOI18N
        ejemploBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBoton4ActionPerformed(evt);
            }
        });
        distribucionFrame.getContentPane().add(ejemploBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 120, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/VARIABLES.jpg"))); // NOI18N
        distribucionFrame.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ejemplocontinuaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton18.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton18.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton18ActionPerformed(evt);
            }
        });
        ejemplocontinuaFrame.getContentPane().add(atrasBoton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        ejemplodiscretaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton19.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton19.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton19ActionPerformed(evt);
            }
        });
        ejemplodiscretaFrame.getContentPane().add(atrasBoton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        ejerciciosFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasBoton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/ATRAS.png"))); // NOI18N
        atrasBoton20.setMaximumSize(new java.awt.Dimension(120, 60));
        atrasBoton20.setMinimumSize(new java.awt.Dimension(120, 60));
        atrasBoton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBoton20ActionPerformed(evt);
            }
        });
        ejerciciosFrame.getContentPane().add(atrasBoton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/INICIAR.png"))); // NOI18N
        iniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 340, 120));

        salirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/SALIR.png"))); // NOI18N
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });
        getContentPane().add(salirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 340, 120));

        creditosBoton.setBackground(new java.awt.Color(153, 255, 255));
        creditosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/CREDITOS.png"))); // NOI18N
        creditosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosBotonActionPerformed(evt);
            }
        });
        getContentPane().add(creditosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 340, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Elementos_Proyecto/PROBABILIDADES.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBotonActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_iniciarBotonActionPerformed

    private void creditosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosBotonActionPerformed
        // TODO add your handling code here:
        creditosFrame.setVisible(true);
        creditosFrame.setSize(1280, 760);
        creditosFrame.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_creditosBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(false);
        this.setVisible(true);        
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void historiaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaBotonActionPerformed
        // TODO add your handling code here: 
        historiaFrame.setVisible(true);
        historiaFrame.setSize(1280, 760);
        historiaFrame.setLocationRelativeTo(null);
        iniciarFrame.setVisible(false);
    }//GEN-LAST:event_historiaBotonActionPerformed

    private void teoriaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teoriaBotonActionPerformed
        // TODO add your handling code here:
        teoriaFrame.setVisible(true);
        teoriaFrame.setSize(1280, 760);
        teoriaFrame.setLocationRelativeTo(null);
        iniciarFrame.setVisible(false);
    }//GEN-LAST:event_teoriaBotonActionPerformed

    private void ejerciciosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejerciciosBotonActionPerformed
        // TODO add your handling code here:
        ejerciciosFrame.setVisible(true);
        ejerciciosFrame.setSize(1280, 760);
        ejerciciosFrame.setLocationRelativeTo(null);
        iniciarFrame.setVisible(false);
    }//GEN-LAST:event_ejerciciosBotonActionPerformed

    private void atrasBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton1ActionPerformed
        // TODO add your handling code here:
        creditosFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_atrasBoton1ActionPerformed

    private void atrasBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton2ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        historiaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton2ActionPerformed

    private void pag2BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag2BotonActionPerformed
        // TODO add your handling code here: 
        historiaFrame1.setVisible(true);
        historiaFrame1.setSize(1280, 760);
        historiaFrame1.setLocationRelativeTo(null);
        historiaFrame.setVisible(false);
    }//GEN-LAST:event_pag2BotonActionPerformed

    private void pag3BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag3BotonActionPerformed
        // TODO add your handling code here:
        historiaFrame2.setVisible(true);
        historiaFrame2.setSize(1280, 760);
        historiaFrame2.setLocationRelativeTo(null);
        historiaFrame1.setVisible(false);
        
    }//GEN-LAST:event_pag3BotonActionPerformed

    private void pag1BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag1BotonActionPerformed
        // TODO add your handling code here:
        historiaFrame.setVisible(true);
        historiaFrame.setSize(1280, 760);
        historiaFrame.setLocationRelativeTo(null);
        historiaFrame1.setVisible(false);
    }//GEN-LAST:event_pag1BotonActionPerformed

    private void atrasBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton3ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        historiaFrame1.setVisible(false);
    }//GEN-LAST:event_atrasBoton3ActionPerformed

    private void atrasBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton4ActionPerformed
            // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        historiaFrame2.setVisible(false);
    }//GEN-LAST:event_atrasBoton4ActionPerformed

    private void pag4BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag4BotonActionPerformed
        // TODO add your handling code here:
        historiaFrame3.setVisible(true);
        historiaFrame3.setSize(1280, 760);
        historiaFrame3.setLocationRelativeTo(null);
        historiaFrame2.setVisible(false);
    }//GEN-LAST:event_pag4BotonActionPerformed

    private void pag2Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag2Boton1ActionPerformed
        // TODO add your handling code here:
        historiaFrame1.setVisible(true);
        historiaFrame1.setSize(1280, 760);
        historiaFrame1.setLocationRelativeTo(null);
        historiaFrame2.setVisible(false);
        
    }//GEN-LAST:event_pag2Boton1ActionPerformed

    private void atrasBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton5ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        historiaFrame3.setVisible(false);
    }//GEN-LAST:event_atrasBoton5ActionPerformed

    private void pag3Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag3Boton1ActionPerformed
        // TODO add your handling code here:
        historiaFrame2.setVisible(true);
        historiaFrame2.setSize(1280, 760);
        historiaFrame2.setLocationRelativeTo(null);
        historiaFrame3.setVisible(false);
    }//GEN-LAST:event_pag3Boton1ActionPerformed

    private void pag5BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag5BotonActionPerformed
        // TODO add your handling code here:
        historiaFrame4.setVisible(true);
        historiaFrame4.setSize(1280, 760);
        historiaFrame4.setLocationRelativeTo(null);
        historiaFrame3.setVisible(false);
    }//GEN-LAST:event_pag5BotonActionPerformed

    private void atrasBoton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton6ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        historiaFrame4.setVisible(false);
    }//GEN-LAST:event_atrasBoton6ActionPerformed

    private void pag4Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag4Boton1ActionPerformed
        // TODO add your handling code here:
        historiaFrame3.setVisible(true);
        historiaFrame3.setSize(1280, 760);
        historiaFrame3.setLocationRelativeTo(null);
        historiaFrame4.setVisible(false);
    }//GEN-LAST:event_pag4Boton1ActionPerformed

    private void atrasBoton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton7ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        teoriaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton7ActionPerformed

    private void atrasBoton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton8ActionPerformed
        // TODO add your handling code here:
        teoriaFrame.setVisible(true);
        teoriaFrame.setSize(1280, 760);
        teoriaFrame.setLocationRelativeTo(null);
        reglasFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton8ActionPerformed

    private void sumaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBotonActionPerformed
        // TODO add your handling code here:
        sumaFrame.setVisible(true);
        sumaFrame.setSize(1280, 760);
        sumaFrame.setLocationRelativeTo(null);
        reglasFrame.setVisible(false);
    }//GEN-LAST:event_sumaBotonActionPerformed

    private void multiplicacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionBotonActionPerformed
        // TODO add your handling code here:
        multiplicacionFrame.setVisible(true);
        multiplicacionFrame.setSize(1280, 760);
        multiplicacionFrame.setLocationRelativeTo(null);
        reglasFrame.setVisible(false);
    }//GEN-LAST:event_multiplicacionBotonActionPerformed

    private void laplaceBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laplaceBotonActionPerformed
        // TODO add your handling code here:
        laplaceFrame.setVisible(true);
        laplaceFrame.setSize(1280, 760);
        laplaceFrame.setLocationRelativeTo(null);
        reglasFrame.setVisible(false);
    }//GEN-LAST:event_laplaceBotonActionPerformed

    private void atrasBoton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton9ActionPerformed
        // TODO add your handling code here:
        reglasFrame.setVisible(true);
        reglasFrame.setSize(1280, 760);
        reglasFrame.setLocationRelativeTo(null);
        sumaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton9ActionPerformed

    private void ejemploBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBotonActionPerformed
        // TODO add your handling code here:
        ejemplosumaFrame.setVisible(true);
        ejemplosumaFrame.setSize(1280, 760);
        ejemplosumaFrame.setLocationRelativeTo(null);
        sumaFrame.setVisible(false);
    }//GEN-LAST:event_ejemploBotonActionPerformed

    private void atrasBoton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton10ActionPerformed
        // TODO add your handling code here:
        sumaFrame.setVisible(true);
        sumaFrame.setSize(1280, 760);
        sumaFrame.setLocationRelativeTo(null);
        ejemplosumaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton10ActionPerformed

    private void reglasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglasBotonActionPerformed
        // TODO add your handling code here:
        reglasFrame.setVisible(true);
        reglasFrame.setSize(1280, 760);
        reglasFrame.setLocationRelativeTo(null);
        teoriaFrame.setVisible(false);
    }//GEN-LAST:event_reglasBotonActionPerformed

    private void conceptosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptosBotonActionPerformed
        // TODO add your handling code here:
        conceptosFrame.setVisible(true);
        conceptosFrame.setSize(1280, 760);
        conceptosFrame.setLocationRelativeTo(null);
        teoriaFrame.setVisible(false);
    }//GEN-LAST:event_conceptosBotonActionPerformed

    private void distribucionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribucionBotonActionPerformed
        // TODO add your handling code here:
        distribucionFrame.setVisible(true);
        distribucionFrame.setSize(1280, 760);
        distribucionFrame.setLocationRelativeTo(null);
        teoriaFrame.setVisible(false);
    }//GEN-LAST:event_distribucionBotonActionPerformed

    private void atrasBoton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton11ActionPerformed
        // TODO add your handling code here:
        reglasFrame.setVisible(true);
        reglasFrame.setSize(1280, 760);
        reglasFrame.setLocationRelativeTo(null);
        multiplicacionFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton11ActionPerformed

    private void atrasBoton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton12ActionPerformed
        // TODO add your handling code here:
        multiplicacionFrame.setVisible(true);
        multiplicacionFrame.setSize(1280, 760);
        multiplicacionFrame.setLocationRelativeTo(null);
        ejemplomultiplicacionFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton12ActionPerformed

    private void ejemploBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBoton1ActionPerformed
        // TODO add your handling code here:
        ejemplomultiplicacionFrame.setVisible(true);
        ejemplomultiplicacionFrame.setSize(1280, 760);
        ejemplomultiplicacionFrame.setLocationRelativeTo(null);
        multiplicacionFrame.setVisible(false);
    }//GEN-LAST:event_ejemploBoton1ActionPerformed

    private void atrasBoton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton13ActionPerformed
        // TODO add your handling code here:
        reglasFrame.setVisible(true);
        reglasFrame.setSize(1280, 760);
        reglasFrame.setLocationRelativeTo(null);
        laplaceFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton13ActionPerformed

    private void ejemploBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBoton2ActionPerformed
        // TODO add your handling code here:
        ejemplolaplaceFrame.setVisible(true);
        ejemplolaplaceFrame.setSize(1280, 760);
        ejemplolaplaceFrame.setLocationRelativeTo(null);
        laplaceFrame.setVisible(false);
    }//GEN-LAST:event_ejemploBoton2ActionPerformed

    private void atrasBoton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton14ActionPerformed
        // TODO add your handling code here:
        laplaceFrame.setVisible(true);
        laplaceFrame.setSize(1280, 760);
        laplaceFrame.setLocationRelativeTo(null);
        ejemplolaplaceFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton14ActionPerformed

    private void atrasBoton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton15ActionPerformed
        // TODO add your handling code here:
        teoriaFrame.setVisible(true);
        teoriaFrame.setSize(1280, 760);
        teoriaFrame.setLocationRelativeTo(null);
        conceptosFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton15ActionPerformed

    private void atrasBoton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton16ActionPerformed
        // TODO add your handling code here:
        teoriaFrame.setVisible(true);
        teoriaFrame.setSize(1280, 760);
        teoriaFrame.setLocationRelativeTo(null);
        conceptosFrame1.setVisible(false);
    }//GEN-LAST:event_atrasBoton16ActionPerformed

    private void siguienteBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBoton3ActionPerformed
        // TODO add your handling code here:
        conceptosFrame1.setVisible(true);
        conceptosFrame1.setSize(1280, 760);
        conceptosFrame1.setLocationRelativeTo(null);
        conceptosFrame.setVisible(false);
    }//GEN-LAST:event_siguienteBoton3ActionPerformed

    private void anteriorBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBoton4ActionPerformed
        // TODO add your handling code here:
        conceptosFrame.setVisible(true);
        conceptosFrame.setSize(1280, 760);
        conceptosFrame.setLocationRelativeTo(null);
        conceptosFrame1.setVisible(false);
    }//GEN-LAST:event_anteriorBoton4ActionPerformed

    private void atrasBoton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton17ActionPerformed
        // TODO add your handling code here:
        teoriaFrame.setVisible(true);
        teoriaFrame.setSize(1280, 760);
        teoriaFrame.setLocationRelativeTo(null);
        distribucionFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton17ActionPerformed

    private void ejemploBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBoton3ActionPerformed
        // TODO add your handling code here:
        ejemplocontinuaFrame.setVisible(true);
        ejemplocontinuaFrame.setSize(1280, 760);
        ejemplocontinuaFrame.setLocationRelativeTo(null);
        distribucionFrame.setVisible(false);
    }//GEN-LAST:event_ejemploBoton3ActionPerformed

    private void ejemploBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBoton4ActionPerformed
        // TODO add your handling code here:
        ejemplodiscretaFrame.setVisible(true);
        ejemplodiscretaFrame.setSize(1280, 760);
        ejemplodiscretaFrame.setLocationRelativeTo(null);
        distribucionFrame.setVisible(false);
    }//GEN-LAST:event_ejemploBoton4ActionPerformed

    private void atrasBoton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton18ActionPerformed
        // TODO add your handling code here:
        distribucionFrame.setVisible(true);
        distribucionFrame.setSize(1280, 760);
        distribucionFrame.setLocationRelativeTo(null);
        ejemplocontinuaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton18ActionPerformed

    private void atrasBoton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton19ActionPerformed
        // TODO add your handling code here:
        distribucionFrame.setVisible(true);
        distribucionFrame.setSize(1280, 760);
        distribucionFrame.setLocationRelativeTo(null);
        ejemplodiscretaFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton19ActionPerformed

    private void atrasBoton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBoton20ActionPerformed
        // TODO add your handling code here:
        iniciarFrame.setVisible(true);
        iniciarFrame.setSize(1280, 760);
        iniciarFrame.setLocationRelativeTo(null);
        ejerciciosFrame.setVisible(false);
    }//GEN-LAST:event_atrasBoton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Probabilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Probabilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Probabilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Probabilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Probabilidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBoton4;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JButton atrasBoton1;
    private javax.swing.JButton atrasBoton10;
    private javax.swing.JButton atrasBoton11;
    private javax.swing.JButton atrasBoton12;
    private javax.swing.JButton atrasBoton13;
    private javax.swing.JButton atrasBoton14;
    private javax.swing.JButton atrasBoton15;
    private javax.swing.JButton atrasBoton16;
    private javax.swing.JButton atrasBoton17;
    private javax.swing.JButton atrasBoton18;
    private javax.swing.JButton atrasBoton19;
    private javax.swing.JButton atrasBoton2;
    private javax.swing.JButton atrasBoton20;
    private javax.swing.JButton atrasBoton3;
    private javax.swing.JButton atrasBoton4;
    private javax.swing.JButton atrasBoton5;
    private javax.swing.JButton atrasBoton6;
    private javax.swing.JButton atrasBoton7;
    private javax.swing.JButton atrasBoton8;
    private javax.swing.JButton atrasBoton9;
    private javax.swing.JButton conceptosBoton;
    private javax.swing.JFrame conceptosFrame;
    private javax.swing.JFrame conceptosFrame1;
    private javax.swing.JButton creditosBoton;
    private javax.swing.JFrame creditosFrame;
    private javax.swing.JButton distribucionBoton;
    private javax.swing.JFrame distribucionFrame;
    private javax.swing.JButton ejemploBoton;
    private javax.swing.JButton ejemploBoton1;
    private javax.swing.JButton ejemploBoton2;
    private javax.swing.JButton ejemploBoton3;
    private javax.swing.JButton ejemploBoton4;
    private javax.swing.JFrame ejemplocontinuaFrame;
    private javax.swing.JFrame ejemplodiscretaFrame;
    private javax.swing.JFrame ejemplolaplaceFrame;
    private javax.swing.JFrame ejemplomultiplicacionFrame;
    private javax.swing.JFrame ejemplosumaFrame;
    private javax.swing.JButton ejerciciosBoton;
    private javax.swing.JFrame ejerciciosFrame;
    private javax.swing.JButton historiaBoton;
    private javax.swing.JFrame historiaFrame;
    private javax.swing.JFrame historiaFrame1;
    private javax.swing.JFrame historiaFrame2;
    private javax.swing.JFrame historiaFrame3;
    private javax.swing.JFrame historiaFrame4;
    private javax.swing.JButton iniciarBoton;
    private javax.swing.JFrame iniciarFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton laplaceBoton;
    private javax.swing.JFrame laplaceFrame;
    private javax.swing.JButton multiplicacionBoton;
    private javax.swing.JFrame multiplicacionFrame;
    private javax.swing.JButton pag1Boton;
    private javax.swing.JButton pag2Boton;
    private javax.swing.JButton pag2Boton1;
    private javax.swing.JButton pag3Boton;
    private javax.swing.JButton pag3Boton1;
    private javax.swing.JButton pag4Boton;
    private javax.swing.JButton pag4Boton1;
    private javax.swing.JButton pag5Boton;
    private javax.swing.JButton reglasBoton;
    private javax.swing.JFrame reglasFrame;
    private javax.swing.JButton salirBoton;
    private javax.swing.JButton siguienteBoton3;
    private javax.swing.JButton sumaBoton;
    private javax.swing.JFrame sumaFrame;
    private javax.swing.JButton teoriaBoton;
    private javax.swing.JFrame teoriaFrame;
    // End of variables declaration//GEN-END:variables
}